declare const EXLYTICS_URL: string
declare const EXLYTICS_ACCOUNT: string
const _EXLYTICS_URL = EXLYTICS_URL
const _EXLYTICS_ACCOUNT = EXLYTICS_ACCOUNT

export { _EXLYTICS_URL as EXLYTICS_URL, _EXLYTICS_ACCOUNT as EXLYTICS_ACCOUNT }